/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MateriaPrimaRec;

import MateriaPrima.MateriaPirmaGUI;
import Modelos.MateriaPrimaRecM;
import Modelos.Usuarios;
import Servicios.Conexion;
import Servicios.MateriaPrimaRec_servicio;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject;

public class MateriaPirmaRecGUI extends javax.swing.JFrame {

    private final MateriaPrimaRec_servicio materiaprimarec_servicio = new MateriaPrimaRec_servicio();
    private List<MateriaPrimaRecM> mpr;

    private final toExcel excel = new toExcel();
    TableRowSorter trs;
    Usuarios mod;
    Connection conexion;

    public String direcciomImg = "img\\jc.png";

    //Imagen de firma
    public String direcciomImg2 = "img\\firma.gif";

    public MateriaPirmaRecGUI() throws SQLException, ClassNotFoundException {
        this.conexion = Conexion.getInstance().getConnection();
        initComponents();
        this.setResizable(false);
        this.setDefaultCloseOperation(0);
        this.MateriaPrimaRecGUI();

        jButton4.setVisible(false);

        //Boton Exportar Materia Prima Recibida
        btnExportarExcel.setFocusPainted(false);
        btnExportarExcel.setBorderPainted(false);
        //jButton1.setContentAreaFilled(false);

        //Boton Regresar
        btnRegresar.setFocusPainted(false);
        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
    }

    public MateriaPirmaRecGUI(Usuarios mod) throws SQLException, ClassNotFoundException {
        this.conexion = Conexion.getInstance().getConnection();
        initComponents();
        this.setDefaultCloseOperation(0);
        this.mod = mod;
        this.setResizable(false);
        this.MateriaPrimaRecGUI();
        this.tblMateriaPrimaRecibida.setDefaultRenderer(Object.class, new MiRenderer());
        jButton4.setVisible(false);

        //Boton Exportar Materia Prima Recibida
        btnExportarExcel.setFocusPainted(false);
        btnExportarExcel.setBorderPainted(false);
        //jButton1.setContentAreaFilled(false);

        //Boton Regresar
        btnRegresar.setFocusPainted(false);
        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        if (mod.getId_tipo() == 4) {
            btnModificar.setEnabled(false);
            jButton4.setEnabled(false);
        }
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("jc/img/jc.png"));

        return retValue;
    }

    private void MateriaPrimaRecGUI() {
        try {

            this.mpr = this.materiaprimarec_servicio.recuperarTodas(conexion);
            DefaultTableModel dtm = (DefaultTableModel) tblMateriaPrimaRecibida.getModel();
            dtm.setRowCount(0);
            for (int i = 0; i < this.mpr.size(); i++) {
                dtm.addRow(new Object[]{
                    this.mpr.get(i).getId(),
                    this.mpr.get(i).getOrdenCompra(),
                    this.mpr.get(i).getCalibre(),
                    this.mpr.get(i).getProveedores(),
                    this.mpr.get(i).getKgSolicitados(),
                    this.mpr.get(i).getKgRecibidos(),
                    this.mpr.get(i).getFactura(),
                    this.mpr.get(i).getFechaRecibida(),});
            }

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(this, "Ha surgido un error y no se han podido recuperar los registros");
        }
    }

    public void Filtro() {
        int ColumnaTabla = 0;
        trs.setRowFilter(RowFilter.regexFilter(jtxtfiltro.getText(), ColumnaTabla, 1, 2, 3));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMateriaPrimaRecibida = new javax.swing.JTable();
        lblMPRecibida = new javax.swing.JLabel();
        jtxtfiltro = new javax.swing.JTextField();
        lblBuscarIcono = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        lblMateriaPrima = new javax.swing.JLabel();
        btnExportarExcel = new javax.swing.JButton();
        lblExportar = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lblJCIcono = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnActualizarPDF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblMateriaPrimaRecibida.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblMateriaPrimaRecibida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "ORDEN COMPRA", "CALIBRE", "PROVEEDOR", "KG./H. SOLICITADOS", "KG./H.  RECIBIDOS", "FACTURA", "FECHA RECIBIDA"
            }
        ));
        jScrollPane1.setViewportView(tblMateriaPrimaRecibida);
        if (tblMateriaPrimaRecibida.getColumnModel().getColumnCount() > 0) {
            tblMateriaPrimaRecibida.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblMateriaPrimaRecibida.getColumnModel().getColumn(2).setPreferredWidth(100);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 1140, 430));

        lblMPRecibida.setFont(new java.awt.Font("Wide Latin", 1, 24)); // NOI18N
        lblMPRecibida.setText("RECIBIDA");
        getContentPane().add(lblMPRecibida, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, -1, 40));

        jtxtfiltro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtfiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtfiltroActionPerformed(evt);
            }
        });
        jtxtfiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtfiltroKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtfiltroKeyTyped(evt);
            }
        });
        getContentPane().add(jtxtfiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 160, 230, -1));

        lblBuscarIcono.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblBuscarIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/buscar.png"))); // NOI18N
        getContentPane().add(lblBuscarIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 160, -1, -1));

        btnRegresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/boton_regresar.png"))); // NOI18N
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 120, 60));

        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/modificar.png"))); // NOI18N
        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 150, 40));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/modificar.png"))); // NOI18N
        jButton4.setText("MODIFICAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 150, 40));

        lblMateriaPrima.setFont(new java.awt.Font("Wide Latin", 1, 24)); // NOI18N
        lblMateriaPrima.setText("MATERIA PRIMA");
        getContentPane().add(lblMateriaPrima, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, -1, 40));

        btnExportarExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/excel.png"))); // NOI18N
        btnExportarExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarExcelActionPerformed(evt);
            }
        });
        getContentPane().add(btnExportarExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 10, 60, 60));

        lblExportar.setText("EXPORTAR");
        getContentPane().add(lblExportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 70, -1, -1));

        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/1004733.png"))); // NOI18N
        btnAgregar.setText("AGREGAR");
        btnAgregar.setMaximumSize(new java.awt.Dimension(128, 40));
        btnAgregar.setMinimumSize(new java.awt.Dimension(128, 40));
        btnAgregar.setPreferredSize(new java.awt.Dimension(128, 40));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, 40));

        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/Eliminar.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, -1, 40));

        lblJCIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/jcLogo.png"))); // NOI18N
        getContentPane().add(lblJCIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(135, 206, 235));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnActualizarPDF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnActualizarPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/PDF.png"))); // NOI18N
        btnActualizarPDF.setText("<html>Actualizar<br/>Orden</html>");
        btnActualizarPDF.setMaximumSize(new java.awt.Dimension(128, 40));
        btnActualizarPDF.setMinimumSize(new java.awt.Dimension(128, 40));
        btnActualizarPDF.setPreferredSize(new java.awt.Dimension(128, 40));
        btnActualizarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarPDFActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizarPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, -1, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtfiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtfiltroActionPerformed
    }//GEN-LAST:event_jtxtfiltroActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        try {
            MateriaPirmaGUI mn = new MateriaPirmaGUI(mod);
            mn.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(MateriaPirmaRecGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MateriaPirmaRecGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void jtxtfiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtfiltroKeyReleased
    }//GEN-LAST:event_jtxtfiltroKeyReleased

    private void jtxtfiltroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtfiltroKeyTyped
        jtxtfiltro.addKeyListener(new KeyAdapter() {
            //@Override
            public void keyReleased(final KeyEvent ke) {
                String cadena = (jtxtfiltro.getText());
                jtxtfiltro.setText(cadena);
                Filtro();
            }
        });
        trs = new TableRowSorter(tblMateriaPrimaRecibida.getModel());
        tblMateriaPrimaRecibida.setRowSorter(trs);
        btnModificar.setVisible(false);
        jButton4.setVisible(true);
    }//GEN-LAST:event_jtxtfiltroKeyTyped

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int fila_seleccionada = tblMateriaPrimaRecibida.getSelectedRow();
        if (fila_seleccionada >= 0) {
            try {
                MateriaPirmaRecGUI.this.dispose();
                ModificarMateriaPrimaRec modificar = new ModificarMateriaPrimaRec(this.mpr.get(fila_seleccionada), mod);
                modificar.setVisible(true);
                modificar.setLocationRelativeTo(null);
            } catch (SQLException ex) {
                Logger.getLogger(MateriaPirmaRecGUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(MateriaPirmaRecGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor seleccione una fila.");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            int fila_seleccionada = trs.convertRowIndexToModel(tblMateriaPrimaRecibida.getSelectedRow());
            if (fila_seleccionada >= 0) {

                MateriaPirmaRecGUI.this.dispose();
                ModificarMateriaPrimaRec modificar = new ModificarMateriaPrimaRec(this.mpr.get(fila_seleccionada), mod);
                modificar.setVisible(true);
                modificar.setLocationRelativeTo(null);

            } else {
                JOptionPane.showMessageDialog(this, "Por favor seleccione una fila.");
            }
        } catch (SQLException ex) {
            Logger.getLogger(MateriaPirmaRecGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MateriaPirmaRecGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnExportarExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarExcelActionPerformed
        excel.WriteExcelMateriaPrimaRecibida();
        JOptionPane.showMessageDialog(this, "Datos Exportados.");
    }//GEN-LAST:event_btnExportarExcelActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
            int fila_seleccionada = tblMateriaPrimaRecibida.getSelectedRow();
            if (fila_seleccionada != -1) {
                int id = (int) tblMateriaPrimaRecibida.getValueAt(fila_seleccionada, 0);
                int resp = JOptionPane.showConfirmDialog(null, "¿ESTAS SEGURO QUE DESEAS ELIMINAR?", "ALERTA!", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);

                if (resp == JOptionPane.YES_NO_OPTION) {
                    this.materiaprimarec_servicio.eliminar(id);

                    MateriaPirmaRecGUI.this.dispose();
                    JOptionPane.showMessageDialog(this, "DATOS ELIMINADOS");

                    MateriaPirmaRecGUI mp = new MateriaPirmaRecGUI(mod);
                    mp.setVisible(true);
                    mp.setLocationRelativeTo(null);

                }
            } else {
                JOptionPane.showMessageDialog(this, "Por favor seleccione una fila.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error.");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        try {
            MateriaPirmaRecGUI.this.dispose();
            AgregarMateriaPrimaRec vista = new AgregarMateriaPrimaRec(mod);
            vista.setVisible(true);
            vista.setLocationRelativeTo(null);
        } catch (SQLException ex) {
            Logger.getLogger(MateriaPirmaGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MateriaPirmaGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    public void ActualizarOrden(int ordenCompra) throws IOException, SQLException {
        try (PDDocument doc = new PDDocument()) {
            PDPage page = new PDPage();
            doc.addPage(page);
            String nameFinal;

            //Imagen logo
            try (PDPageContentStream contentStream = new PDPageContentStream(doc, page)) {
                PDImageXObject pdImage = PDImageXObject.createFromFile(direcciomImg, doc);
                contentStream.drawImage(pdImage, 20, 650, 120, 120);
                contentStream.beginText();
                contentStream.setFont(PDType1Font.HELVETICA, 16);
                contentStream.newLineAtOffset(280, page.getMediaBox().getHeight() - 30);
                contentStream.showText("Jorge De Jesus Cobian Ordoñez");
                contentStream.endText();

                contentStream.beginText();
                contentStream.setFont(PDType1Font.HELVETICA, 16);
                contentStream.newLineAtOffset(280, page.getMediaBox().getHeight() - 50);
                contentStream.showText("Circuito Norte 1 y 3 dentro del parque  Ind.");
                contentStream.endText();

                contentStream.beginText();
                contentStream.setFont(PDType1Font.HELVETICA, 16);
                contentStream.newLineAtOffset(280, page.getMediaBox().getHeight() - 70);
                contentStream.showText("Zapotlán 2000");
                contentStream.endText();

                contentStream.beginText();
                contentStream.setFont(PDType1Font.HELVETICA, 16);
                contentStream.newLineAtOffset(280, page.getMediaBox().getHeight() - 90);
                contentStream.showText("CD Guzmán, Jalisco");
                contentStream.endText();

                contentStream.beginText();
                contentStream.setFont(PDType1Font.HELVETICA, 16);
                contentStream.newLineAtOffset(280, page.getMediaBox().getHeight() - 110);
                contentStream.showText("CP 49000");
                contentStream.endText();

                contentStream.beginText();
                contentStream.setFont(PDType1Font.HELVETICA, 16);
                contentStream.newLineAtOffset(280, page.getMediaBox().getHeight() - 130);
                contentStream.showText("Tel (341) 1330-717");
                contentStream.endText();

                contentStream.moveTo(30, 620);
                contentStream.lineTo(590, 620);
                contentStream.stroke();

                //Fecha actual
                LocalDate fechaA = LocalDate.now();

                contentStream.beginText();
                contentStream.setFont(PDType1Font.HELVETICA, 16);
                contentStream.newLineAtOffset(35, page.getMediaBox().getHeight() - 190);
                contentStream.showText("Fecha: " + fechaA);
                contentStream.endText();

                contentStream.beginText();
                contentStream.setFont(PDType1Font.HELVETICA_BOLD, 16);
                contentStream.newLineAtOffset(270, page.getMediaBox().getHeight() - 190);
                contentStream.showText("ORDEN DE COMPRA ");
                contentStream.endText();

                contentStream.beginText();
                contentStream.setFont(PDType1Font.HELVETICA_BOLD, 14);
                contentStream.newLineAtOffset(490, page.getMediaBox().getHeight() - 190);
                contentStream.showText(String.valueOf(ordenCompra));
                contentStream.endText();

                contentStream.beginText();
                contentStream.setFont(PDType1Font.HELVETICA_BOLD, 14);
                contentStream.newLineAtOffset(35, page.getMediaBox().getHeight() - 230);
                contentStream.showText("Proveedor");
                contentStream.endText();
                java.sql.Statement st = conexion.createStatement();
                //Nombre del proveedor
                String sqlOrdenCompra = "SELECT proveedor FROM mprecibida WHERE ordenCompra='" + ordenCompra + "' ";//si falla poner comillas dobles
                ResultSet rs = st.executeQuery(sqlOrdenCompra);
                String nomProv = null;
                while (rs.next()) {
                    nomProv = rs.getString("proveedor");
                    contentStream.beginText();
                    contentStream.setFont(PDType1Font.HELVETICA, 13);
                    contentStream.newLineAtOffset(35, page.getMediaBox().getHeight() - 245);
                    contentStream.showText(nomProv);
                    contentStream.endText();
                }
                //colonia del proovedor
                String sql2 = "SELECT colonia FROM proveedores WHERE proveedores.nombre='" + nomProv + "' LIMIT 1";
                ResultSet rs2 = st.executeQuery(sql2);
                while (rs2.next()) {
                    String ColProv = rs2.getString("colonia");
                    contentStream.beginText();
                    contentStream.setFont(PDType1Font.HELVETICA, 13);
                    contentStream.newLineAtOffset(35, page.getMediaBox().getHeight() - 260);
                    contentStream.showText(ColProv);
                    contentStream.endText();
                }
                //parque 
                //colonia del proovedor
                String sqlPar = "SELECT parque FROM proveedores WHERE proveedores.nombre='" + nomProv + "' LIMIT 1";
                ResultSet rsPar = st.executeQuery(sqlPar);
                while (rsPar.next()) {
                    String parque = rsPar.getString("parque");
                    contentStream.beginText();
                    contentStream.setFont(PDType1Font.HELVETICA, 13);
                    contentStream.newLineAtOffset(35, page.getMediaBox().getHeight() - 275);
                    contentStream.showText(parque);
                    contentStream.endText();
                }
                //cp del proovedor
                String sql3 = "SELECT codigoPostal FROM proveedores WHERE proveedores.nombre='" + nomProv + "' LIMIT 1";
                ResultSet rs3 = st.executeQuery(sql3);
                while (rs3.next()) {
                    String CPprov = rs3.getString("codigoPostal");
                    contentStream.beginText();
                    contentStream.setFont(PDType1Font.HELVETICA, 13);
                    contentStream.newLineAtOffset(35, page.getMediaBox().getHeight() - 290);
                    contentStream.showText("C.P. " + CPprov);
                    contentStream.endText();
                }
                //ciudad, estado, pais del proovedor
                String Cprov = null;
                String Eprov = null;
                String Pprov = null;
                String sqlC = "SELECT ciudad FROM proveedores WHERE proveedores.nombre='" + nomProv + "' LIMIT 1";
                ResultSet rsC = st.executeQuery(sqlC);
                while (rsC.next()) {
                    Cprov = rsC.getString("ciudad");
                }
                String sqlE = "SELECT estado FROM proveedores WHERE proveedores.nombre='" + nomProv + "' LIMIT 1";
                ResultSet rsE = st.executeQuery(sqlE);
                while (rsE.next()) {
                    Eprov = rsE.getString("estado");
                }
                String sqlP = "SELECT pais FROM proveedores WHERE proveedores.nombre='" + nomProv + "' LIMIT 1";
                ResultSet rsP = st.executeQuery(sqlP);
                while (rsP.next()) {
                    Pprov = rsP.getString("pais");
                }

                contentStream.beginText();
                contentStream.setFont(PDType1Font.HELVETICA, 13);
                contentStream.newLineAtOffset(35, page.getMediaBox().getHeight() - 305);
                contentStream.showText(Cprov + ", " + Eprov + ", " + Pprov);
                contentStream.endText();

                //Liena inferior X
                contentStream.moveTo(30, 482);
                contentStream.lineTo(590, 482);
                contentStream.stroke();

                //Linea izquierda Y
                contentStream.moveTo(30, 482);
                contentStream.lineTo(30, 620);
                contentStream.stroke();

                //Linea derecha Y
                contentStream.moveTo(590, 482);
                contentStream.lineTo(590, 620);
                contentStream.stroke();

                //Segunda tabla
                //Liena inferior X
                contentStream.moveTo(30, 470);
                contentStream.lineTo(590, 470);
                contentStream.stroke();

                //Descripcion
                contentStream.beginText();
                contentStream.setFont(PDType1Font.HELVETICA_BOLD, 13);
                contentStream.newLineAtOffset(35, page.getMediaBox().getHeight() - 335);
                contentStream.showText("Descripción: ");
                contentStream.endText();

                contentStream.moveTo(30, 450);
                contentStream.lineTo(590, 450);
                contentStream.stroke();

                contentStream.moveTo(30, 170);
                contentStream.lineTo(30, 470);
                contentStream.stroke();

                contentStream.beginText();
                contentStream.setFont(PDType1Font.HELVETICA_BOLD, 12);
                contentStream.newLineAtOffset(40, page.getMediaBox().getHeight() - 370);
                contentStream.showText("Calibre");
                contentStream.endText();

                contentStream.moveTo(90, 280);
                contentStream.lineTo(90, 450);
                contentStream.stroke();

                contentStream.beginText();
                contentStream.setFont(PDType1Font.HELVETICA_BOLD, 12);
                contentStream.newLineAtOffset(160, page.getMediaBox().getHeight() - 370);
                contentStream.showText("Descripción");
                contentStream.endText();

                contentStream.moveTo(310, 280);
                contentStream.lineTo(310, 450);
                contentStream.stroke();

                contentStream.beginText();
                contentStream.setFont(PDType1Font.HELVETICA_BOLD, 12);
                contentStream.newLineAtOffset(320, page.getMediaBox().getHeight() - 370);
                contentStream.showText("P. U.");
                contentStream.endText();

                contentStream.moveTo(380, 280);
                contentStream.lineTo(380, 450);
                contentStream.stroke();

                contentStream.beginText();
                contentStream.setFont(PDType1Font.HELVETICA_BOLD, 12);
                contentStream.newLineAtOffset(382, page.getMediaBox().getHeight() - 370);
                contentStream.showText("Moneda");
                contentStream.endText();

                contentStream.moveTo(430, 280);
                contentStream.lineTo(430, 450);
                contentStream.stroke();

                contentStream.beginText();
                contentStream.setFont(PDType1Font.HELVETICA_BOLD, 12);
                contentStream.newLineAtOffset(438, page.getMediaBox().getHeight() - 370);
                contentStream.showText("No. Calibre");
                contentStream.endText();

                contentStream.moveTo(510, 280);
                contentStream.lineTo(510, 450);
                contentStream.stroke();

                contentStream.beginText();
                contentStream.setFont(PDType1Font.HELVETICA_BOLD, 12);
                contentStream.newLineAtOffset(516, page.getMediaBox().getHeight() - 370);
                contentStream.showText("Cantidad Kg");
                contentStream.endText();

                contentStream.moveTo(590, 170);
                contentStream.lineTo(590, 470);
                contentStream.stroke();

                contentStream.moveTo(30, 418);
                contentStream.lineTo(590, 418);
                contentStream.stroke();

                contentStream.moveTo(30, 400);
                contentStream.lineTo(590, 400);
                contentStream.stroke();

                String sqlCali = "SELECT proveedores.calibre FROM proveedores, mprecibida WHERE mprecibida.calibre=proveedores.calibre AND proveedores.nombre='" + nomProv + "' AND mprecibida.ordenCompra='" + ordenCompra + "'";
                ResultSet rsCali = st.executeQuery(sqlCali);
                List<String> calibres = new ArrayList<>();

                while (rsCali.next()) {
                    String calibre = rsCali.getString("calibre");
                    calibres.add(calibre);
                }

                String cali1 = calibres.size() > 0 ? calibres.get(0) : "";
                String cali2 = calibres.size() > 1 ? calibres.get(1) : "";
                String cali3 = calibres.size() > 2 ? calibres.get(2) : "";
                String cali4 = calibres.size() > 3 ? calibres.get(3) : "";
                String cali5 = calibres.size() > 4 ? calibres.get(4) : "";
                String cali6 = calibres.size() > 5 ? calibres.get(5) : "";
                String cali7 = calibres.size() > 6 ? calibres.get(6) : "";

                //Descripción de Productos
                String[] listCalibres = {cali1, cali2, cali3, cali4, cali5, cali6, cali7};
                String[] descripciones = new String[listCalibres.length];

                for (int i = 0; i < listCalibres.length; i++) {
                    String sqlD = "SELECT descripcion FROM inventario, materia_prima, proveedores WHERE inventario.calibre=materia_prima.calibre AND materia_prima.calibre_proveedor= proveedores.calibre AND proveedores.nombre='" + nomProv + "' AND materia_prima.calibre='" + listCalibres[i] + "'";
                    ResultSet rsD = st.executeQuery(sqlD);
                    if (rsD.next()) {
                        descripciones[i] = rsD.getString("descripcion");
                    } else {
                        descripciones[i] = "";
                    }
                }

                //Número de Calibre
                String[] numCalibres = new String[listCalibres.length];

                for (int i = 0; i < numCalibres.length; i++) {
                    String sqlNCal = "SELECT num_calibre FROM inventario, materia_prima, proveedores WHERE inventario.calibre= materia_prima.calibre AND inventario.calibre= proveedores.calibre AND proveedores.nombre='" + nomProv + "' AND materia_prima.calibre='" + listCalibres[i] + "'";
                    ResultSet rsNCal = st.executeQuery(sqlNCal);
                    if (rsNCal.next()) {
                        numCalibres[i] = rsNCal.getString("num_calibre");
                    } else {
                        numCalibres[i] = "";
                    }
                }

                // Kg Solicitados
                String[] kgSolicitados = new String[listCalibres.length];
                for (int i = 0; i < kgSolicitados.length; i++) {
                    String sqlKg = "SELECT kgSolicitados FROM mprecibida, proveedores WHERE mprecibida.calibre=proveedores.calibre AND proveedores.nombre='" + nomProv + "' AND mprecibida.calibre='" + listCalibres[i] + "' AND mprecibida.ordenCompra='" + ordenCompra + "'";
                    ResultSet rsKg = st.executeQuery(sqlKg);
                    if (rsKg.next() == true) {
                        kgSolicitados[i] = rsKg.getString("kgSolicitados");
                    } else {
                        kgSolicitados[i] = "";
                    }
                }

                //Peso y moneda
                String[] mCalibre = new String[listCalibres.length];
                String[] pCalibre = new String[listCalibres.length];
                if (mCalibre.length == pCalibre.length) {
                    for (int i = 0; i < mCalibre.length; i++) {
                        String sqlIdProv = "SELECT id_prov FROM proveedores WHERE nombre='" + nomProv + "' AND calibre='" + listCalibres[i] + "'";
                        ResultSet rsIdProv = st.executeQuery(sqlIdProv);
                        if (rsIdProv.next()) {
                            String sqlMp = "SELECT pesoUnitario,moneda FROM preciomp WHERE id_prov='" + rsIdProv.getInt("id_prov") + "'";
                            ResultSet rsmp = st.executeQuery(sqlMp);
                            if (rsmp.next()) {
                                mCalibre[i] = rsmp.getString("moneda");
                                pCalibre[i] = rsmp.getString("pesoUnitario");
                            } else {
                                mCalibre[i] = "";
                                pCalibre[i] = "";
                            }
                        } else {
                            mCalibre[i] = "";
                            pCalibre[i] = "";
                        }
                    }
                }

                for (int i = 0; i < listCalibres.length; i++) {
                    String calibre = listCalibres[i];
                    if (calibre != null && !calibre.isEmpty()) {
                        float offset = 390 + (i * 20); // Ajustar el offset en función del índice

                        // calibre
                        contentStream.beginText();
                        contentStream.setFont(PDType1Font.HELVETICA_BOLD, 10);
                        contentStream.newLineAtOffset(31, page.getMediaBox().getHeight() - offset);
                        contentStream.showText(listCalibres[i]);
                        contentStream.endText();

                        // descripcion
                        contentStream.beginText();
                        contentStream.setFont(PDType1Font.HELVETICA, 10);
                        contentStream.newLineAtOffset(92, page.getMediaBox().getHeight() - offset);
                        contentStream.showText(descripciones[i]);
                        contentStream.endText();

                        // Peso
                        contentStream.beginText();
                        contentStream.setFont(PDType1Font.HELVETICA, 10);
                        contentStream.newLineAtOffset(320, page.getMediaBox().getHeight() - offset);
                        contentStream.showText(pCalibre[i]);
                        contentStream.endText();

                        // Moneda
                        contentStream.beginText();
                        contentStream.setFont(PDType1Font.HELVETICA, 10);
                        contentStream.newLineAtOffset(390, page.getMediaBox().getHeight() - offset);
                        contentStream.showText(mCalibre[i]);
                        contentStream.endText();

                        // num Cali
                        contentStream.beginText();
                        contentStream.setFont(PDType1Font.HELVETICA, 10);
                        contentStream.newLineAtOffset(445, page.getMediaBox().getHeight() - offset);
                        contentStream.showText(numCalibres[i]);
                        contentStream.endText();

                        contentStream.beginText();
                        contentStream.setFont(PDType1Font.HELVETICA, 10);
                        contentStream.newLineAtOffset(518, page.getMediaBox().getHeight() - offset);
                        contentStream.showText(kgSolicitados[i]);
                        contentStream.endText();
                    }
                }

                contentStream.moveTo(30, 380);
                contentStream.lineTo(590, 380);
                contentStream.stroke();

                contentStream.moveTo(30, 360);
                contentStream.lineTo(590, 360);
                contentStream.stroke();

                contentStream.moveTo(30, 340);
                contentStream.lineTo(590, 340);
                contentStream.stroke();

                contentStream.moveTo(30, 320);
                contentStream.lineTo(590, 320);
                contentStream.stroke();

                contentStream.moveTo(30, 300);
                contentStream.lineTo(590, 300);
                contentStream.stroke();

                contentStream.moveTo(30, 280);
                contentStream.lineTo(590, 280);
                contentStream.stroke();

                if (nomProv.equals("B.F STEEL DE MEXICO S.A DE C.V")) {
                    contentStream.beginText();
                    contentStream.setFont(PDType1Font.HELVETICA_BOLD, 12);
                    contentStream.newLineAtOffset(40, page.getMediaBox().getHeight() - 530);
                    contentStream.showText("Presentación:");
                    contentStream.endText();

                    String sqlPres = "SELECT inventario.unidad FROM inventario, materia_prima, proveedores WHERE materia_prima.aprobacion='SOLICITAR' AND inventario.calibre= materia_prima.calibre AND inventario.calibre= proveedores.calibre AND proveedores.nombre='" + nomProv + "'";
                    ResultSet rsPres = st.executeQuery(sqlPres);
                    String pres = null;
                    if (rsPres.next() == true) {
                        pres = rsPres.getString("unidad");
                        contentStream.beginText();
                        contentStream.setFont(PDType1Font.HELVETICA, 12);
                        contentStream.newLineAtOffset(250, page.getMediaBox().getHeight() - 530);
                        contentStream.showText(pres);
                        contentStream.endText();
                    }
                    String sqlPres2 = "SELECT inventario.unidad FROM inventario, materia_prima, proveedores WHERE materia_prima.aprobacion='SOLICITAR' AND inventario.calibre= materia_prima.calibre AND inventario.calibre= proveedores.calibre AND proveedores.nombre='" + nomProv + "' AND  materia_prima.calibre!='" + cali1 + "' AND inventario.unidad!='" + pres + "'";
                    ResultSet rsPres2 = st.executeQuery(sqlPres2);
                    if (rsPres2.next() == true) {
                        String pres2 = rsPres2.getString("unidad");
                        contentStream.beginText();
                        contentStream.setFont(PDType1Font.HELVETICA, 12);
                        contentStream.newLineAtOffset(250, page.getMediaBox().getHeight() - 540);
                        contentStream.showText(pres2);
                        contentStream.endText();
                    }
                    contentStream.setNonStrokingColor(Color.RED);

                    contentStream.beginText();
                    contentStream.setFont(PDType1Font.HELVETICA_BOLD, 12);
                    contentStream.newLineAtOffset(40, page.getMediaBox().getHeight() - 570);
                    contentStream.showText("Nota: Dureza máxima 48 HRB");
                    contentStream.endText();

                    contentStream.setNonStrokingColor(Color.BLACK);

                    contentStream.beginText();
                    contentStream.setFont(PDType1Font.HELVETICA_BOLD, 12);
                    contentStream.newLineAtOffset(40, page.getMediaBox().getHeight() - 600);
                    contentStream.showText("Cantidad Total:");
                    contentStream.endText();

                    int cantTotal = 0;
                    for (int i = 0; i < kgSolicitados.length; i++) {
                        if (!kgSolicitados[i].isEmpty()) {
                            cantTotal += Integer.parseInt(kgSolicitados[i]);
                        }
                    }

                    String totalCadena = String.valueOf(cantTotal);
                    contentStream.beginText();
                    contentStream.setFont(PDType1Font.HELVETICA_BOLD, 12);
                    contentStream.newLineAtOffset(250, page.getMediaBox().getHeight() - 600);
                    contentStream.showText(totalCadena + "  kgs");
                    contentStream.endText();

                    contentStream.beginText();
                    contentStream.setFont(PDType1Font.HELVETICA_BOLD, 12);
                    contentStream.newLineAtOffset(40, page.getMediaBox().getHeight() - 620);
                    contentStream.showText("Crédito: 30 días");
                    contentStream.endText();

                    contentStream.moveTo(30, 170);
                    contentStream.lineTo(590, 170);
                    contentStream.stroke();

                    contentStream.beginText();
                    contentStream.setFont(PDType1Font.HELVETICA_BOLD, 12);
                    contentStream.newLineAtOffset(450, page.getMediaBox().getHeight() - 650);
                    contentStream.showText("PLANEACIÓN");
                    contentStream.endText();

                    contentStream.moveTo(400, 70);
                    contentStream.lineTo(590, 70);
                    contentStream.stroke();

                    PDImageXObject pdImageFirma = PDImageXObject.createFromFile(direcciomImg2, doc);

                    contentStream.drawImage(pdImageFirma, 412, 55, 130, 120);

                    contentStream.beginText();
                    contentStream.setFont(PDType1Font.HELVETICA_BOLD, 12);
                    contentStream.newLineAtOffset(410, page.getMediaBox().getHeight() - 735);
                    contentStream.showText("SILVIA MONROY CHAGOLLA");
                    contentStream.endText();

                    contentStream.beginText();
                    contentStream.setFont(PDType1Font.HELVETICA_BOLD, 8);
                    contentStream.newLineAtOffset(530, page.getMediaBox().getHeight() - 780);
                    contentStream.showText("F - CO 02 REV 01");
                    contentStream.endText();

                } else if (nomProv.equals("Aceros Especiales Magaña")) {
                    contentStream.beginText();
                    contentStream.setFont(PDType1Font.HELVETICA_BOLD, 12);
                    contentStream.newLineAtOffset(40, page.getMediaBox().getHeight() - 510);
                    contentStream.showText("Presentación:");
                    contentStream.endText();

                    String sqlPres = "SELECT inventario.unidad FROM inventario, materia_prima, proveedores WHERE materia_prima.aprobacion='SOLICITAR' AND inventario.calibre= materia_prima.calibre AND inventario.calibre= proveedores.calibre AND proveedores.nombre='" + nomProv + "'";
                    ResultSet rsPres = st.executeQuery(sqlPres);
                    String pres = null;
                    if (rsPres.next() == true) {
                        pres = rsPres.getString("unidad");
                        contentStream.beginText();
                        contentStream.setFont(PDType1Font.HELVETICA, 12);
                        contentStream.newLineAtOffset(250, page.getMediaBox().getHeight() - 510);
                        contentStream.showText(pres);
                        contentStream.endText();
                    }

                    String sqlPres2 = "SELECT inventario.unidad FROM inventario, materia_prima, proveedores WHERE materia_prima.aprobacion='SOLICITAR' AND inventario.calibre= materia_prima.calibre AND inventario.calibre= proveedores.calibre AND proveedores.nombre='" + nomProv + "' AND  materia_prima.calibre!='" + cali1 + "' AND inventario.unidad!='" + pres + "'";
                    ResultSet rsPres2 = st.executeQuery(sqlPres2);
                    if (rsPres2.next() == true) {
                        String pres2 = rsPres2.getString("unidad");
                        contentStream.beginText();
                        contentStream.setFont(PDType1Font.HELVETICA, 12);
                        contentStream.newLineAtOffset(250, page.getMediaBox().getHeight() - 550);
                        contentStream.showText(pres2);
                        contentStream.endText();
                    }

                    contentStream.beginText();
                    contentStream.setFont(PDType1Font.HELVETICA, 12);
                    contentStream.newLineAtOffset(40, page.getMediaBox().getHeight() - 550);
                    contentStream.setNonStrokingColor(Color.red);
                    contentStream.showText("Nota: Este material se Recoge en Hojas.");
                    contentStream.endText();

                    contentStream.beginText();
                    contentStream.setFont(PDType1Font.HELVETICA_BOLD, 12);
                    contentStream.setNonStrokingColor(Color.black);
                    contentStream.newLineAtOffset(40, page.getMediaBox().getHeight() - 580);
                    contentStream.showText("Cantidad Total:");
                    contentStream.endText();

                    int cantTotal = 0;
                    for (int i = 0; i < kgSolicitados.length; i++) {
                        if (!kgSolicitados[i].isEmpty()) {
                            cantTotal += Integer.parseInt(kgSolicitados[i]);
                        }
                    }

                    String totalCadena = String.valueOf(cantTotal);
                    contentStream.beginText();
                    contentStream.setFont(PDType1Font.HELVETICA_BOLD, 12);
                    contentStream.newLineAtOffset(250, page.getMediaBox().getHeight() - 580);
                    contentStream.showText(totalCadena + "  Hojas");
                    contentStream.endText();

                    contentStream.beginText();
                    contentStream.setFont(PDType1Font.HELVETICA_BOLD, 12);
                    contentStream.newLineAtOffset(40, page.getMediaBox().getHeight() - 600);
                    contentStream.showText("Crédito: 30 días");
                    contentStream.endText();

                    contentStream.moveTo(30, 180);
                    contentStream.lineTo(590, 180);
                    contentStream.stroke();

                    contentStream.beginText();
                    contentStream.setFont(PDType1Font.HELVETICA_BOLD, 12);
                    contentStream.newLineAtOffset(450, page.getMediaBox().getHeight() - 650);
                    contentStream.showText("PLANEACIÓN");
                    contentStream.endText();

                    contentStream.moveTo(400, 90);
                    contentStream.lineTo(590, 90);
                    contentStream.stroke();

                    PDImageXObject pdImageFirma = PDImageXObject.createFromFile(direcciomImg2, doc);

                    contentStream.drawImage(pdImageFirma, 412, 55, 130, 120);

                    contentStream.beginText();
                    contentStream.setFont(PDType1Font.HELVETICA_BOLD, 12);
                    contentStream.newLineAtOffset(410, page.getMediaBox().getHeight() - 725);
                    contentStream.showText("SILVIA MONROY CHAGOLLA");
                    contentStream.endText();

                    contentStream.beginText();
                    contentStream.setFont(PDType1Font.HELVETICA_BOLD, 8);
                    contentStream.newLineAtOffset(530, page.getMediaBox().getHeight() - 780);
                    contentStream.showText("F - CO 02 REV 01");
                    contentStream.endText();
                } else {
                    contentStream.beginText();
                    contentStream.setFont(PDType1Font.HELVETICA_BOLD, 12);
                    contentStream.newLineAtOffset(40, page.getMediaBox().getHeight() - 530);
                    contentStream.showText("Presentación:");
                    contentStream.endText();

                    String sqlPres = "SELECT inventario.unidad FROM inventario, materia_prima, proveedores WHERE materia_prima.aprobacion='SOLICITAR' AND inventario.calibre= materia_prima.calibre AND inventario.calibre= proveedores.calibre AND proveedores.nombre='" + nomProv + "' ";
                    ResultSet rsPres = st.executeQuery(sqlPres);
                    String pres = null;
                    if (rsPres.next() == true) {
                        pres = rsPres.getString("unidad");
                        contentStream.beginText();
                        contentStream.setFont(PDType1Font.HELVETICA, 12);
                        contentStream.newLineAtOffset(250, page.getMediaBox().getHeight() - 530);
                        contentStream.showText(pres);
                        contentStream.endText();
                    }

                    String sqlPres2 = "SELECT inventario.unidad FROM inventario, materia_prima, proveedores WHERE materia_prima.aprobacion='SOLICITAR' AND inventario.calibre= materia_prima.calibre AND inventario.calibre= proveedores.calibre AND proveedores.nombre='Serviacero Planos S de RL de CV' AND  materia_prima.calibre!='" + cali1 + "' AND inventario.unidad!='" + pres + "'";
                    ResultSet rsPres2 = st.executeQuery(sqlPres2);
                    if (rsPres2.next() == true) {
                        String pres2 = rsPres2.getString("unidad");
                        contentStream.beginText();
                        contentStream.setFont(PDType1Font.HELVETICA, 12);
                        contentStream.newLineAtOffset(250, page.getMediaBox().getHeight() - 550);
                        contentStream.showText(pres2);
                        contentStream.endText();
                    }

                    contentStream.beginText();
                    contentStream.setFont(PDType1Font.HELVETICA_BOLD, 12);
                    contentStream.newLineAtOffset(40, page.getMediaBox().getHeight() - 580);
                    contentStream.showText("Cantidad Total:");
                    contentStream.endText();

                    int cantTotal = 0;
                    for (int i = 0; i < kgSolicitados.length; i++) {
                        if (!kgSolicitados[i].isEmpty()) {
                            cantTotal += Integer.parseInt(kgSolicitados[i]);
                        }
                    }

                    String totalCadena = String.valueOf(cantTotal);
                    contentStream.beginText();
                    contentStream.setFont(PDType1Font.HELVETICA_BOLD, 12);
                    contentStream.newLineAtOffset(250, page.getMediaBox().getHeight() - 580);
                    contentStream.showText(totalCadena + "  kgs");
                    contentStream.endText();

                    contentStream.beginText();
                    contentStream.setFont(PDType1Font.HELVETICA_BOLD, 12);
                    contentStream.newLineAtOffset(40, page.getMediaBox().getHeight() - 600);
                    contentStream.showText("Crédito: 30 días");
                    contentStream.endText();

                    contentStream.moveTo(30, 170);
                    contentStream.lineTo(590, 170);
                    contentStream.stroke();

                    contentStream.beginText();
                    contentStream.setFont(PDType1Font.HELVETICA_BOLD, 12);
                    contentStream.newLineAtOffset(450, page.getMediaBox().getHeight() - 650);
                    contentStream.showText("PLANEACIÓN");
                    contentStream.endText();

                    contentStream.moveTo(400, 70);
                    contentStream.lineTo(590, 70);
                    contentStream.stroke();

                    //SERVIDOR
                    PDImageXObject pdImageFirma = PDImageXObject.createFromFile(direcciomImg2, doc);

                    contentStream.drawImage(pdImageFirma, 412, 55, 130, 120);

                    contentStream.beginText();
                    contentStream.setFont(PDType1Font.HELVETICA_BOLD, 12);
                    contentStream.newLineAtOffset(410, page.getMediaBox().getHeight() - 735);
                    contentStream.showText("SILVIA MONROY CHAGOLLA");
                    contentStream.endText();

                    contentStream.beginText();
                    contentStream.setFont(PDType1Font.HELVETICA_BOLD, 8);
                    contentStream.newLineAtOffset(530, page.getMediaBox().getHeight() - 780);
                    contentStream.showText("F - CO 02 REV 01");
                    contentStream.endText();
                }
                nameFinal = nomProv;
            }
            JOptionPane.showMessageDialog(this, "Orden Actualizada");
            doc.save(ordenCompra + "-" + nameFinal + ".pdf");
        }
    }

    private void btnActualizarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarPDFActionPerformed
        int ordenCompra = Integer.parseInt(JOptionPane.showInputDialog("Ingresa la orden de Compra"));
        try {
            this.ActualizarOrden(ordenCompra);
        } catch (IOException ex) {
            Logger.getLogger(MateriaPirmaRecGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MateriaPirmaRecGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnActualizarPDFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MateriaPirmaRecGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MateriaPirmaRecGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MateriaPirmaRecGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MateriaPirmaRecGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MateriaPirmaRecGUI().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(MateriaPirmaRecGUI.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(MateriaPirmaRecGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarPDF;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnExportarExcel;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtxtfiltro;
    private javax.swing.JLabel lblBuscarIcono;
    private javax.swing.JLabel lblExportar;
    private javax.swing.JLabel lblJCIcono;
    private javax.swing.JLabel lblMPRecibida;
    private javax.swing.JLabel lblMateriaPrima;
    private javax.swing.JTable tblMateriaPrimaRecibida;
    // End of variables declaration//GEN-END:variables
}
