/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AlmacenInspeccion;

import Modelos.InspeccionM;
import Modelos.Usuarios;
import Servicios.Conexion;
import Servicios.Inspeccion_servicio;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class InspeccionGUI extends javax.swing.JFrame {

    private final Inspeccion_servicio ins_servicio = new Inspeccion_servicio();
    private List<InspeccionM> ins;

    Usuarios mod;
    TableRowSorter trs;
    Connection conexion;

    public InspeccionGUI() throws SQLException, ClassNotFoundException {
        this.conexion = Conexion.getInstance().getConnection();
        initComponents();
        this.setResizable(false);
        this.INS();
        this.setDefaultCloseOperation(0);
        jButton4.setVisible(false);
    }

    public InspeccionGUI(Usuarios mod) throws SQLException, ClassNotFoundException {
        this.conexion = Conexion.getInstance().getConnection();
        initComponents();
        this.mod = mod;
        this.setResizable(false);
        this.setDefaultCloseOperation(0);
        this.INS();

        jButton4.setVisible(false);
        if (mod.getId_tipo() == 4) {
            btnSalida.setEnabled(false);
            jButton4.setEnabled(false);
        }
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("jc/img/jc.png"));

        return retValue;
    }

    private void INS() {
        try {
            this.ins = this.ins_servicio.recuperarTodas(conexion);

            DefaultTableModel dtm = (DefaultTableModel) tblInspeccion.getModel();
            dtm.setRowCount(0);
            for (int i = 0; i < this.ins.size(); i++) {
                dtm.addRow(new Object[]{
                    this.ins.get(i).getComponente(),
                    this.ins.get(i).getExistencia(),
                    this.ins.get(i).getEntrada(),
                    this.ins.get(i).getFechaEntrada(),
                    this.ins.get(i).getSalida()
                });
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(this, "Ha surgido un error y no se han podido recuperar los registros");
        }
    }

    public void Filtro() {
        int ColumnaTabla = 0;
        trs.setRowFilter(RowFilter.regexFilter(jtxtfiltro.getText(), ColumnaTabla, 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalida = new javax.swing.JButton();
        jtxtfiltro = new javax.swing.JTextField();
        lblBuscarIcono = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblInspeccion = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        lblJCIcono = new javax.swing.JLabel();
        lblEntSalInspeccion = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalida.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/modificar.png"))); // NOI18N
        btnSalida.setText("SALIDA");
        btnSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 150, 30));

        jtxtfiltro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtfiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtfiltroActionPerformed(evt);
            }
        });
        jtxtfiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtfiltroKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtfiltroKeyTyped(evt);
            }
        });
        getContentPane().add(jtxtfiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 140, 180, -1));

        lblBuscarIcono.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblBuscarIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/buscar.png"))); // NOI18N
        getContentPane().add(lblBuscarIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 140, 30, -1));

        btnCerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/cancelar.png"))); // NOI18N
        btnCerrar.setText("CERRAR");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 130, 40));

        tblInspeccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "COMPONENTE", "EXISTENCIA", "ENTRADA", "FECHA ENTRADA", "SALIDA"
            }
        ));
        tblInspeccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblInspeccionKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tblInspeccion);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 1110, 320));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/modificar.png"))); // NOI18N
        jButton4.setText("SALIDA");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 150, 30));

        lblJCIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/jcLogo.png"))); // NOI18N
        getContentPane().add(lblJCIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblEntSalInspeccion.setFont(new java.awt.Font("Wide Latin", 1, 24)); // NOI18N
        lblEntSalInspeccion.setForeground(new java.awt.Color(0, 0, 0));
        lblEntSalInspeccion.setText("<html><center>ENTRADA Y SALIDA <br>DE ALMACEN(INSPECCIÓN)</center></html>");
        getContentPane().add(lblEntSalInspeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(135, 206, 235));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaActionPerformed
        try {
            Statement comando = conexion.createStatement();
            int fila_seleccionada = tblInspeccion.getSelectedRow();
            if (fila_seleccionada >= 0) {
                String componente = (String) tblInspeccion.getValueAt(fila_seleccionada, 0);
                ResultSet registroP = comando.executeQuery("SELECT * FROM almaceninspeccion WHERE componente= '" + componente + "' AND existencia!=''");

                if (registroP.next() == true) {
                    InspeccionGUI.this.dispose();
                    Salida modificar = new Salida(this.ins.get(fila_seleccionada), mod);
                    modificar.setVisible(true);
                    modificar.setLocationRelativeTo(null);
                } else {
                    JOptionPane.showMessageDialog(this, "NO HAY EXISTENCIA EN ALMACEN.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Por favor seleccione una fila.");
            }
        } catch (SQLException ex) {
            Logger.getLogger(InspeccionGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InspeccionGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSalidaActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void jtxtfiltroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtfiltroKeyTyped
        jtxtfiltro.addKeyListener(new KeyAdapter() {
            //@Override
            public void keyReleased(final KeyEvent ke) {
                String cadena = (jtxtfiltro.getText());
                jtxtfiltro.setText(cadena);
                Filtro();
            }
        });
        trs = new TableRowSorter(tblInspeccion.getModel());
        tblInspeccion.setRowSorter(trs);
        jButton4.setVisible(true);
        btnSalida.setVisible(false);

    }//GEN-LAST:event_jtxtfiltroKeyTyped

    private void jtxtfiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtfiltroKeyReleased
    }//GEN-LAST:event_jtxtfiltroKeyReleased

    private void jtxtfiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtfiltroActionPerformed
    }//GEN-LAST:event_jtxtfiltroActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int fila_seleccionada = trs.convertRowIndexToModel(tblInspeccion.getSelectedRow());
        if (fila_seleccionada >= 0) {
            try {
                InspeccionGUI.this.dispose();
                Salida modificar = new Salida(this.ins.get(fila_seleccionada), mod);
                modificar.setVisible(true);
                modificar.setLocationRelativeTo(null);
            } catch (SQLException ex) {
                Logger.getLogger(InspeccionGUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(InspeccionGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor seleccione una fila.");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tblInspeccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblInspeccionKeyReleased
        if (evt.getKeyCode() == com.sun.glass.events.KeyEvent.VK_ENTER) {
            try {
                String componente = tblInspeccion.getValueAt(tblInspeccion.getSelectedRow(), 0).toString();
                String cr = tblInspeccion.getValueAt(tblInspeccion.getSelectedRow(), 1).toString();
                PreparedStatement consulta;
                consulta = conexion.prepareStatement("UPDATE crs SET cr='" + cr + "' WHERE componente='" + componente + "'");
                consulta.executeUpdate();
                JOptionPane.showMessageDialog(this, "MODIFICACIÓN EXITOSA");
            } catch (SQLException ex) {
                Logger.getLogger(InspeccionGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tblInspeccionKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InspeccionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InspeccionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InspeccionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InspeccionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new InspeccionGUI().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(InspeccionGUI.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(InspeccionGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnSalida;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jtxtfiltro;
    private javax.swing.JLabel lblBuscarIcono;
    private javax.swing.JLabel lblEntSalInspeccion;
    private javax.swing.JLabel lblJCIcono;
    private javax.swing.JTable tblInspeccion;
    // End of variables declaration//GEN-END:variables
}
